// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtrsfnsgchstizxxnfok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0cnNmbnNnY2hzdGl6eHhuZm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NTYwODgsImV4cCI6MjA4NjIzMjA4OH0.v3KTkJDPtBq_wiTLSj7XC16ER_xbvKvvj7PrYtIj-Xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});